package GALS;

public interface Constants extends ScannerConstants, ParserConstants
{
    int EPSILON  = 0;
    int DOLLAR   = 1;

    int t_MULTI_LINE_COMMENT = 2;
    int t_ONE_LINE_COMMENT = 3;
    int t_BOOL_KEYWORD = 4;
    int t_VOID_KEYWORD = 5;
    int t_INT_KEYWORD = 6;
    int t_FLOAT_KEYWORD = 7;
    int t_DOUBLE_KEYWORD = 8;
    int t_CHAR_KEYWORD = 9;
    int t_STRING_KEYWORD = 10;
    int t_IF_KEYWORD = 11;
    int t_ELSE_KEYWORD = 12;
    int t_SWITCH_KEYWORD = 13;
    int t_CASE_KEYWORD = 14;
    int t_BREAK_KEYWORD = 15;
    int t_DEFAULT_KEYWORD = 16;
    int t_DO_KEYWORD = 17;
    int t_WHILE_KEYWORD = 18;
    int t_FOR_KEYWORD = 19;
    int t_RETURN_KEYWORD = 20;
    int t_CIN_KEYWORD = 21;
    int t_COUT_KEYWORD = 22;
    int t_STATIC_KEYWORD = 23;
    int t_CONST_KEYWORD = 24;
    int t_NEW_KEYWORD = 25;
    int t_ENDL_KEYWORD = 26;
    int t_INT_LITERAL = 27;
    int t_FLOAT_LITERAL = 28;
    int t_CHAR_LITERAL = 29;
    int t_STRING_LITERAL = 30;
    int t_BOOL_LITERAL = 31;
    int t_NULL_LITERAL = 32;
    int t_PLUS = 33;
    int t_MINUS = 34;
    int t_TIMES = 35;
    int t_DIVIDE = 36;
    int t_MODULO = 37;
    int t_INCREMENT = 38;
    int t_DECREMENT = 39;
    int t_EQUAL = 40;
    int t_EQUALS = 41;
    int t_NOT_EQUALS = 42;
    int t_GREATER = 43;
    int t_LESS = 44;
    int t_GREATER_OR_EQUALS = 45;
    int t_LESS_OR_EQUALS = 46;
    int t_LOGICAL_AND = 47;
    int t_LOGICAL_OR = 48;
    int t_LOGICAL_NOT = 49;
    int t_BITWISE_AND = 50;
    int t_BITWISE_OR = 51;
    int t_BITWISE_XOR = 52;
    int t_BITWISE_NOT = 53;
    int t_LEFT_SHIFT = 54;
    int t_RIGHT_SHIFT = 55;
    int t_IDENTIFIER = 56;
    int t_DOT = 57;
    int t_SEMICOLON = 58;
    int t_COLON = 59;
    int t_COMMA = 60;
    int t_LEFT_PARENTHESIS = 61;
    int t_RIGHT_PARENTHESIS = 62;
    int t_LEFT_BRACKET = 63;
    int t_RIGHT_BRACKET = 64;
    int t_LEFT_BRACE = 65;
    int t_RIGHT_BRACE = 66;

}
