package GALS;

import importador.Importador;

public interface ScannerConstants
{
    int[][] SCANNER_TABLE = new Importador().getTabela();

    int[] TOKEN_STATE = { -1,   0,  38,  -1,  26,  39,  -1,  50,  51,  24,  22,  49,  23,  46,  25,  16,  16,  48,  47,  33,  29,  32,  -1,  52,  53,  41,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  54,  40,  55,  42,  31,  19,  -1,  36,  -1,  -1,  27,  28,  17,  -1,   3,  17,  -1,  -1,  43,  35,  30,  34,  44,  45,  45,  45,  45,  45,  45,  45,  45,  11,  45,  45,  45,  45,  45,  45,  45,  37,  19,  18,  17,  -1,  16,  16,  45,  45,  45,  45,  45,  45,  14,   6,  45,  45,  45,  45,  45,  45,   2,   4,   9,  45,  12,  45,  45,  45,  45,  45,  20,   5,  45,  45,   7,  45,  45,  45,  13,   8,  45,  15,  10,  21 };

    String[] SCANNER_ERROR =
    {
        "Caractere não esperado",
        "",
        "",
        "Erro identificando STRING_LITERAL",
        "",
        "",
        "Erro identificando CHAR_LITERAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando IDENTIFIER",
        "",
        "",
        "",
        "Erro identificando IDENTIFIER ou BOOL_KEYWORD",
        "Erro identificando IDENTIFIER ou CHAR_KEYWORD",
        "Erro identificando IDENTIFIER ou DOUBLE_KEYWORD",
        "Erro identificando IDENTIFIER ou ELSE_KEYWORD",
        "Erro identificando IDENTIFIER ou FOR_KEYWORD ou BOOL_LITERAL ou FLOAT_KEYWORD",
        "Erro identificando IDENTIFIER ou IF_KEYWORD ou INT_KEYWORD",
        "Erro identificando IDENTIFIER ou NULL_LITERAL",
        "Erro identificando IDENTIFIER ou RETURN_KEYWORD",
        "Erro identificando IDENTIFIER ou STRING_KEYWORD",
        "Erro identificando IDENTIFIER ou BOOL_LITERAL",
        "Erro identificando IDENTIFIER ou VOID_KEYWORD",
        "Erro identificando IDENTIFIER ou WHILE_KEYWORD",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando STRING_LITERAL",
        "",
        "Erro identificando CHAR_LITERAL",
        "Erro identificando CHAR_LITERAL",
        "",
        "",
        "",
        "Erro identificando MULTI_LINE_COMMENT",
        "",
        "",
        "Erro identificando INT_LITERAL",
        "Erro identificando INT_LITERAL",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "Erro identificando MULTI_LINE_COMMENT",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        ""
    };

}
